use std::env;
use std::path::{Path, PathBuf};

/// Only target/float-ABI combination this crate currently ships bindings for.
const SUPPORTED_TARGET: &str = "thumbv7em-none-eabihf";

/// Vendored via `update-third-party.sh` — see that script for the pinned nrfxlib version.
const THIRD_PARTY_SUBPATH: &str = "third_party/nordic/nrfxlib/nrf_fuel_gauge";
const LIB_SUBPATH: &str = "lib/cortex-m4/hard-float";
const INCLUDE_SUBPATH: &str = "include";
const LIB_NAME: &str = "nrf_fuel_gauge";

fn main() {
    let target = env::var("TARGET").unwrap();
    if target != SUPPORTED_TARGET {
        println!(
            "cargo:warning=nrf-fuel-gauge-sys only ships linking support for `{SUPPORTED_TARGET}` \
             (Cortex-M4, hard-float, secondary-cell variant of libnrf_fuel_gauge.a). \
             Building for `{target}` will likely fail to link."
        );
    }

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let nrf_fuel_gauge_dir = manifest_dir.join(THIRD_PARTY_SUBPATH);
    let lib_dir = nrf_fuel_gauge_dir.join(LIB_SUBPATH);
    let include_dir = nrf_fuel_gauge_dir.join(INCLUDE_SUBPATH);
    let lib_file = lib_dir.join(format!("lib{LIB_NAME}.a"));

    if !lib_file.is_file() {
        panic!(
            "\n\nCould not find {}.\n\
             The vendored Nordic SDK files are missing — run ./update-third-party.sh from the \
             repo root to fetch them.\n",
            lib_file.display(),
        );
    }

    println!("cargo:rustc-link-search=native={}", lib_dir.display());
    println!("cargo:rustc-link-lib=static={LIB_NAME}");

    compile_battery_model(&include_dir);

    println!("cargo:rerun-if-env-changed=NRF_FUEL_GAUGE_MODEL_PATH");
}

/// Vendored via `update-third-party.sh`: sdk-nrf's nPM1300 fuel gauge sample's generic
/// "Example" battery model, used as the default until a real model is supplied.
const EXAMPLE_MODEL_SUBPATH: &str =
    "third_party/nordic/nrf/samples/pmic/native/npm13xx_fuel_gauge/src/battery_model.inc";

/// Compiles the battery model `.inc` file (as generated by Nordic's nPM PowerUp App) into a
/// small static library exposing `nrf_fuel_gauge_wrapper_model`, which the safe wrapper crate
/// links against. Falls back to Nordic's own generic "Example" model when
/// `NRF_FUEL_GAUGE_MODEL_PATH` is unset, so the crate builds and runs out of the box — but that
/// model is NOT calibrated for any real battery; see the crate's README.
fn compile_battery_model(include_dir: &Path) {
    let model_path = env::var_os("NRF_FUEL_GAUGE_MODEL_PATH").map(PathBuf::from).unwrap_or_else(|| {
        println!(
            "cargo:warning=NRF_FUEL_GAUGE_MODEL_PATH is not set — falling back to Nordic's \
             generic \"Example\" battery model (from the nPM1300 fuel gauge sample). This is NOT \
             calibrated for your battery. Generate a real model with Nordic's nPM PowerUp App \
             and point NRF_FUEL_GAUGE_MODEL_PATH at the resulting .inc file before shipping."
        );
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(EXAMPLE_MODEL_SUBPATH)
    });

    if !model_path.is_file() {
        panic!("Battery model file not found: {}", model_path.display());
    }
    println!("cargo:rerun-if-changed={}", model_path.display());

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let shim_path = out_dir.join("model_shim.c");
    std::fs::write(
        &shim_path,
        format!(
            "#include \"nrf_fuel_gauge.h\"\n\
             const struct battery_model nrf_fuel_gauge_wrapper_model = {{\n\
             #include \"{}\"\n\
             }};\n",
            model_path.display()
        ),
    )
    .expect("failed to write generated battery model shim");

    cc::Build::new()
        .file(&shim_path)
        .include(include_dir)
        .compile("nrf_fuel_gauge_model_shim");
}
