//! Raw FFI bindings to Nordic Semiconductor's nRF Fuel Gauge library, secondary-cell
//! (rechargeable) variant, Cortex-M4 hard-float only.
//!
//! Hand-written rather than bindgen-generated: the upstream header
//! (nrf_fuel_gauge.h from https://github.com/nrfconnect/sdk-nrfxlib/tree/main/nrf_fuel_gauge)
//! is small, and its one anonymous union (`model` / `model_primary` in
//! `nrf_fuel_gauge_init_parameters`) is easier to flatten by hand than to fight through bindgen,
//! since this crate only ever builds the secondary-cell library and never touches the
//! `model_primary` member.
//!
//! The battery model itself (`nrf_fuel_gauge_wrapper_model`) is not defined here — it's compiled
//! in by build.rs from a `.inc` file supplied via `NRF_FUEL_GAUGE_MODEL_PATH`, generated by
//! Nordic's nPM PowerUp App for your specific battery.

#![no_std]
#![allow(non_camel_case_types)]

use core::ffi::{c_char, c_int, c_void};

/// Secondary cell (rechargeable) battery model parameters.
///
/// Field contents are opaque (Nordic ships this as fitted numeric data, not documented
/// individually) — construct this only via a model generated by Nordic's nPM PowerUp App,
/// compiled in through `NRF_FUEL_GAUGE_MODEL_PATH`. Never build one by hand.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct battery_model {
    pub param_1: [f32; 201],
    pub temps: [f32; 3],
    pub param_2: [f32; 122],
    pub param_3: [f32; 201],
    pub param_4: [f32; 201],
    pub param_5: [f32; 201],
    pub param_6: [f32; 201],
    pub param_7: [f32; 122],
    pub param_8: [f32; 122],
    pub param_9: [f32; 3],
    pub param_10: [f32; 6],
    pub param_11: [f32; 6],
    pub param_12: [f32; 3],
    pub name: [c_char; 64],
}

/// Library state information. Useful for debugging.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct nrf_fuel_gauge_state_info {
    pub yhat: f32,
    pub r0: f32,
    pub t_truncated: f32,
    pub i_corrected: f32,
    pub soc_raw: f32,
    pub soh_raw: f32,
    pub cycle_count: u16,
    pub cycle_count_cumulative_mah: f32,
    pub k1: f32,
    pub k2: f32,
}

/// Configuration parameters. See `nrf_fuel_gauge_config_params_default_get` /
/// `nrf_fuel_gauge_config_params_current_get` to obtain a populated value — most fields are
/// purposefully undocumented by Nordic.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct nrf_fuel_gauge_config_parameters {
    pub discard_positive_deltaz: bool,
    pub tte_min_time: f32,
    pub tte_reset_threshold: f32,
    pub soh_estimate_enable: bool,
    pub soh_partial_charge_enable: bool,
    pub soh: f32,
    pub soh_calc_threshold: f32,
    pub battery_min_capacity: f32,
    pub cycle_count: u16,
    pub cycle_count_cumulative_mah: f32,
    pub tau1: f32,
    pub tau2: f32,
    pub neta1: f32,
    pub neta2: f32,
    pub beta1: f32,
    pub beta2: f32,
    pub gating: f32,
    pub volt_drop: f32,
    pub vk_buffer_length: u8,
    pub soh_alpha1: f32,
    pub soh_alpha2: f32,
    pub soh_raw: f32,
    pub a: f32,
    pub b: f32,
    pub c: f32,
    pub d: f32,
    pub cycle_repl_min: f32,
    pub soh_up_cap_cycle_min: f32,
    pub soh_up_max: f32,
    pub soh_rep_up_max: f32,
    pub soh_jump_thr: f32,
    pub soh_partial_min_delta_soc: f32,
    pub soh_partial_r_penalty: f32,
}

/// Library init parameter struct.
///
/// Upstream this contains a union of `model`/`model_primary`; since this crate only builds the
/// secondary-cell library, that union is flattened to a single pointer field. A C union of two
/// pointer-sized, pointer-aligned members has identical layout to one pointer field, so this
/// stays ABI-compatible with the real (secondary-cell-only) struct.
#[repr(C)]
pub struct nrf_fuel_gauge_init_parameters {
    pub v0: f32,
    pub i0: f32,
    pub t0: f32,
    pub model: *const battery_model,
    pub opt_params: *const nrf_fuel_gauge_config_parameters,
    pub lock_func: Option<extern "C" fn(context: *const c_void, lock: bool) -> c_int>,
    pub lock_context: *const c_void,
    pub state: *const c_void,
    pub state_size: usize,
}

/// Charger state enum.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum nrf_fuel_gauge_charge_state {
    Idle = 0,
    Trickle = 1,
    Cc = 2,
    CcLimited = 3,
    Cv = 4,
    Complete = 5,
}

/// State info type used for informing the library of external factors and events.
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum nrf_fuel_gauge_ext_state_info_type {
    VbusConnected = 0,
    VbusDisconnected = 1,
    ChargeStateChange = 2,
    ChargeCurrentCorrection = 3,
    DischargeCurrentCorrection = 4,
    ChargeCurrentLimit = 5,
    TermCurrent = 6,
    BatteryReplaced = 7,
}

/// State info data type used for additional information.
#[repr(C)]
#[derive(Clone, Copy)]
pub union nrf_fuel_gauge_ext_state_info_data {
    pub charge_state: nrf_fuel_gauge_charge_state,
    pub current_correction_factor: f32,
    pub charge_current_limit: f32,
    pub charge_term_current: f32,
}

extern "C" {
    /// Version number of nRF Fuel Gauge library in format "x.y.z".
    pub static nrf_fuel_gauge_version: *const c_char;
    /// Build date of nRF Fuel Gauge library.
    pub static nrf_fuel_gauge_build_date: *const c_char;
    /// Size of the internal state memory used by nRF Fuel Gauge library.
    pub static nrf_fuel_gauge_state_size: usize;

    pub fn nrf_fuel_gauge_config_params_default_get(
        params: *mut nrf_fuel_gauge_config_parameters,
    ) -> c_int;
    pub fn nrf_fuel_gauge_config_params_current_get(
        params: *mut nrf_fuel_gauge_config_parameters,
    ) -> c_int;
    pub fn nrf_fuel_gauge_state_compatible_check(state: *const c_void, state_size: usize) -> c_int;
    pub fn nrf_fuel_gauge_init(
        parameters: *const nrf_fuel_gauge_init_parameters,
        v0: *mut f32,
    ) -> c_int;
    pub fn nrf_fuel_gauge_process(
        v: f32,
        i: f32,
        t: f32,
        t_delta: f32,
        soc: *mut f32,
        state: *mut nrf_fuel_gauge_state_info,
    ) -> c_int;
    pub fn nrf_fuel_gauge_soc_get(soc: *mut f32) -> c_int;
    pub fn nrf_fuel_gauge_tte_get(tte: *mut f32) -> c_int;
    pub fn nrf_fuel_gauge_ttf_get(ttf: *mut f32) -> c_int;
    pub fn nrf_fuel_gauge_soh_get(soh: *mut f32) -> c_int;
    pub fn nrf_fuel_gauge_idle_set(v: f32, t: f32, i_avg: f32) -> c_int;
    pub fn nrf_fuel_gauge_state_get(state: *mut c_void, size: usize) -> c_int;
    pub fn nrf_fuel_gauge_ext_state_update(
        info_type: nrf_fuel_gauge_ext_state_info_type,
        data: *mut nrf_fuel_gauge_ext_state_info_data,
    ) -> c_int;
    pub fn nrf_fuel_gauge_config_params_adjust(
        params: *const nrf_fuel_gauge_config_parameters,
    ) -> c_int;
}

extern "C" {
    /// The battery model compiled in by build.rs from the `.inc` file pointed to by
    /// `NRF_FUEL_GAUGE_MODEL_PATH` (or the bundled non-functional placeholder if unset).
    pub static nrf_fuel_gauge_wrapper_model: battery_model;
}

// These hand-written bindings aren't bindgen-generated, so nothing else catches a struct
// definition here drifting out of sync with Nordic's header. Sizes below were checked against
// nrf_fuel_gauge.h (sdk-nrfxlib, `main` as of 2026-08) by compiling a `sizeof()` probe with
// `arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard`, i.e. this crate's only
// supported target. `nrf_fuel_gauge_init_parameters` is pointer-width dependent (it holds
// pointers/a function pointer), so this assertion only holds on that target.
const _: () = assert!(core::mem::size_of::<battery_model>() == 0x1600);
const _: () = assert!(core::mem::size_of::<nrf_fuel_gauge_state_info>() == 0x28);
const _: () = assert!(core::mem::size_of::<nrf_fuel_gauge_config_parameters>() == 0x80);
#[cfg(target_pointer_width = "32")]
const _: () = assert!(core::mem::size_of::<nrf_fuel_gauge_init_parameters>() == 0x24);
